### ISSUE TITLE
Week 1 (May 29 - Jun 4): Introductions

### ISSUE THREAD

**Issue by shionguha** [marquettecomputationalsocialscience/mkecrimeoutcomedata#1]
1. create github accounts and familiarize yourself with git projects, repos, sending pull requests etc.

2. basic introduction to clustering algorithms
read:

**Comment by qnchenry** [comment]
Hi Dr. Guha ,

I hope the paper is going well. Im very excited to see an email from you in
my inbox. However, I'm a little confused as to the nature of this email to
which I'm replying. Essentially, I'm not seeing an actual message. How's it
going??

Best regards,
Quinci Henry

On Dec 30, 2018 4:47 PM, "Shion" <notifications@github.com> wrote:

Closed #1
<https://github.com/marquettecomputationalsocialscience/mkecrimeoutcomedata/issues/1>
.

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/marquettecomputationalsocialscience/mkecrimeoutcomedata/issues/1#event-2048577802>,
or mute the thread
